# Generated by Django 3.1.1 on 2020-10-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('product_class', models.CharField(choices=[('cream', 'Cream'), ('hair', 'Hair'), ('body', 'Body'), ('face', 'Face')], max_length=60)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
